---
- name: Reset configuration
  hosts: cvp1
  vars_files:
    - ../vars/CVP_model.yml
  tasks:
    - name: Upload configlets to CVP
      arista.cvp.cv_configlet_v3:
        configlets: "{{ CVP_CONFIGLETS }}"
    - name: Apply configlets to devices
      arista.cvp.cv_device_v3:
        devices: "{{ CVP_DEVICES }}"
        state: present
        apply_mode: strict