---
- name: Upload configlets to CVP
  hosts: cvp1
  vars_files:
    - ../vars/CVP_model.yml
  tasks:
    - name: Upload configlets to CVP
      arista.cvp.cv_configlet_v3:
        configlets: "{{ CVP_CONFIGLETS }}"