---
- name: Build fabric configuration
  hosts: FABRIC
  tasks:
    - name: Generate AVD structured configurations and Fabric documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_designs
    - name: Generate device configurations and documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen