---
- name: Deploy fabric to CVP
  hosts: cvp1
  gather_facts: false
  tasks:
    - name: Provision CVP with AVD configuration
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'FABRIC'
        configlets_prefix: 'AVD'
        apply_mode: loose
        state: present
        execute_tasks: false # Set it to true if you want the change to be made without a change control in CVP
        cv_collection: v3